import { Toaster } from "react-hot-toast";
import Header from "./components/header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Toaster
        position="top-right"
      />


      <body className="w-full h-screen">
        <Header />
        {children}
      </body>
    </html>
  );
}
